const INVENTORY_DATA = [
  { room: "Ruang Kelas A", name: "Kursi", qty: "27", code: "01.04.27.1990", condition: "Baik" },
  { room: "Ruang Kelas A", name: "Meja", qty: "1", code: "01.01.12.1990", condition: "Baik" },
  { room: "Ruang Kelas A", name: "Kipas", qty: "1", code: "01.07.07.2000", condition: "Baik" },
  { room: "Ruang Kelas A", name: "LCD", qty: "1", code: "01.06.01.2000", condition: "Baik" },
  { room: "Ruang Kelas A", name: "Papan tulis", qty: "1", code: "01.32.01.2000", condition: "Baik" },
  { room: "Ruang Kelas A", name: "Figuran Visi Misi Teologi", qty: "1", code: "01.07.16.2021", condition: "Baik" },
  { room: "Ruang Kelas A", name: "Figuran visi misi PAK", qty: "1", code: "01.17.17.2018", condition: "Baik" },
  { room: "Ruang Kelas A", name: "Figuran visi misi STTNI", qty: "1", code: "01.17.18.1990", condition: "Baik" },

  { room: "Ruang Kelas B", name: "Kursi", qty: "25", code: "01.04.56.1990", condition: "Baik" },
  { room: "Ruang Kelas B", name: "LCD projector", qty: "1", code: "01.06.02.2000", condition: "Baik" },
  { room: "Ruang Kelas B", name: "Screen", qty: "-", code: "", condition: "" },
  { room: "Ruang Kelas B", name: "Kipas dinding", qty: "1", code: "01.07.08.2000", condition: "Kurang baik" },
  { room: "Ruang Kelas B", name: "Jam dinding", qty: "1", code: "01.11.03.2000", condition: "Baik" },
  { room: "Ruang Kelas B", name: "Meja dosen", qty: "1", code: "01.01.13.1990", condition: "Kurang baik" },
  { room: "Ruang Kelas B", name: "Papan tulis", qty: "1", code: "01.32.02.2000", condition: "Baik" },
  { room: "Ruang Kelas B", name: "Figura visi misi teologi", qty: "1", code: "01.17.19.2021", condition: "Baik" },
  { room: "Ruang Kelas B", name: "Mimbar kampus", qty: "", code: "01.33.01.1990", condition: "-" },

  { room: "Ruang Kelas C", name: "Kursi", qty: "25", code: "01.04.80.1990", condition: "Baik" },
  { room: "Ruang Kelas C", name: "Meja", qty: "1", code: "01.01.14.1990", condition: "Baik" },
  { room: "Ruang Kelas C", name: "LCD", qty: "1", code: "01.06.03.2000", condition: "Baik" },
  { room: "Ruang Kelas C", name: "Kipas", qty: "1", code: "Rusak", condition: "Rusak" },
  { room: "Ruang Kelas C", name: "Papan tulis", qty: "1", code: "01.32.03.2000", condition: "Baik" },
  { room: "Ruang Kelas C", name: "Kursi dosen", qty: "1", code: "01.02.11.2012", condition: "Baik" },
  { room: "Ruang Kelas C", name: "Figura visi misi PAK", qty: "1", code: "01.17.20.2018", condition: "Baik" },
  { room: "Ruang Kelas C", name: "Madding PAK", qty: "1", code: "02.32.07.1990", condition: "Baik" },
  { room: "Ruang Kelas C", name: "Jam dinding", qty: "1", code: "01.11.04.2000", condition: "Mati" },

  { room: "Ruang Kelas D", name: "Kursi", qty: "24", code: "01.04.97.1990", condition: "Baik" },
  { room: "Ruang Kelas D", name: "Meja", qty: "1", code: "01.01.15.1990", condition: "Baik" },
  { room: "Ruang Kelas D", name: "LCD", qty: "", code: "01.06.04.2000", condition: "Rusak akan diganti" },
  { room: "Ruang Kelas D", name: "Kipas", qty: "1", code: "01.07.10.2000", condition: "Rusak" },
  { room: "Ruang Kelas D", name: "Papan tulis", qty: "1", code: "01.32.04.2000", condition: "Baik" },
  { room: "Ruang Kelas D", name: "Mimbar kampus", qty: "1", code: "01.33.02.1990", condition: "Baik" },
  { room: "Ruang Kelas D", name: "Madding", qty: "1", code: "02.32.06.1990", condition: "Baik" },
  { room: "Ruang Kelas D", name: "Figura visi misi", qty: "1", code: "02.17.26.2021", condition: "Baik" },
  { room: "Ruang Kelas D", name: "Wi-Fi", qty: "1", code: "02.15.06.2017", condition: "Baik" },

  { room: "Ruang Kelas E", name: "Kursi", qty: "17", code: "01.04.114.1990", condition: "Baik" },
  { room: "Ruang Kelas E", name: "Meja", qty: "10", code: "01.01.16.1990", condition: "Baik" },
  { room: "Ruang Kelas E", name: "White board", qty: "1", code: "01.32.05.2000", condition: "Baik" },
  { room: "Ruang Kelas E", name: "LCD", qty: "", code: "01.06.05.2021", condition: "Rusak" },
  { room: "Ruang Kelas E", name: "Kipas", qty: "1", code: "01.07.11.2021", condition: "Baik" },
  { room: "Ruang Kelas E", name: "AC", qty: "2", code: "", condition: "Baik" },

  { room: "Ruang Kelas Pasca Sarjana (?)", name: "Kursi mahasiswa", qty: "", code: "01.04.138.2011", condition: "" },
  { room: "Ruang Kelas Pasca Sarjana (?)", name: "Meja dosen", qty: "", code: "01.01.29.1990", condition: "" },
  { room: "Ruang Kelas Pasca Sarjana (?)", name: "Kursi dosen", qty: "", code: "01.02.21.2019", condition: "" },
  { room: "Ruang Kelas Pasca Sarjana (?)", name: "Papan tulis", qty: "", code: "01.32.06.1990", condition: "" },
  { room: "Ruang Kelas Pasca Sarjana (?)", name: "LCD", qty: "", code: "01.06.06.2013", condition: "" },
  { room: "Ruang Kelas Pasca Sarjana (?)", name: "AC", qty: "", code: "01.07.08.2013", condition: "" },
  { room: "Ruang Kelas Pasca Sarjana (?)", name: "Kipas angin", qty: "", code: "01.07.15.2000", condition: "" },
  { room: "Ruang Kelas Pasca Sarjana (?)", name: "Figura foto presiden dan wakil presiden RI", qty: "", code: "01.17.51.2019", condition: "" },
  { room: "Ruang Kelas Pasca Sarjana (?)", name: "Figura visi misi pasca sarjana", qty: "", code: "01.17.52.1996", condition: "" },
  { room: "Ruang Kelas Pasca Sarjana (?)", name: "Figura gambar Yesus", qty: "", code: "01.17.53.2011", condition: "" },
  { room: "Ruang Kelas Pasca Sarjana (?)", name: "Figura foto pasca sarjana", qty: "", code: "01.17.54.2011", condition: "" },
  { room: "Ruang Kelas Pasca Sarjana (?)", name: "Kursi plastic", qty: "", code: "01.04.144.1996", condition: "" },
  { room: "Ruang Kelas Pasca Sarjana (?)", name: "Dispenser", qty: "", code: "01.09.02.2006", condition: "" },
  { room: "Ruang Kelas Pasca Sarjana (?)", name: "Kipas", qty: "", code: "01.07.16.2000", condition: "" },
  { room: "Ruang Kelas Pasca Sarjana (?)", name: "Mading", qty: "", code: "01.32.10.1990", condition: "" },

  { room: "Ruang Ketua", name: "Papan nama dosen", qty: "1", code: "01.17.01.2012", condition: "Baik" },
  { room: "Ruang Ketua", name: "Figura prasetia", qty: "-", code: "01.17.02.2017", condition: "" },
  { room: "Ruang Ketua", name: "AC", qty: "1", code: "01.07.01.2013", condition: "Baik" },
  { room: "Ruang Ketua", name: "Meja kursi dosen", qty: "1", code: "01.01.01.2010", condition: "Baik" },
  { room: "Ruang Ketua", name: "Kursi dosen", qty: "1", code: "01.02.02.2021", condition: "Baik" },
  { room: "Ruang Ketua", name: "Mebel tamu (meja tamu)", qty: "1", code: "01.05.01.2011", condition: "Baik" },
  { room: "Ruang Ketua", name: "Sofa tamu", qty: "1 pjg; 3 pendek", code: "01.05.04.2011", condition: "Baik" },
  { room: "Ruang Ketua", name: "Printer", qty: "1", code: "01.06.01.2013", condition: "Baik" },
  { room: "Ruang Ketua", name: "Kipas angin", qty: "1", code: "01.07.01.2000", condition: "Baik" },
  { room: "Ruang Ketua", name: "Jam dinding", qty: "1", code: "01.11.01.2013", condition: "Baik" },
  { room: "Ruang Ketua", name: "Struktur organisasi", qty: "1", code: "01.17.03.2011", condition: "Baik" },
  { room: "Ruang Ketua", name: "Tempat sampah", qty: "1", code: "01.10.03.2013", condition: "Baik" },
  { room: "Ruang Ketua", name: "Kursi kampus", qty: "1", code: "01.34.10.2012", condition: "Baik" },
  { room: "Ruang Ketua", name: "Rak buku", qty: "1", code: "01.18.01.2012", condition: "Baik" },

  { room: "Ruang WK I Bidang Akademik", name: "Meja kursi dosen", qty: "1", code: "01.01.30.1990", condition: "Baik" },
  { room: "Ruang WK I Bidang Akademik", name: "Kursi kerja dosen", qty: "1", code: "01.02.22.2012", condition: "Baik" },
  { room: "Ruang WK I Bidang Akademik", name: "Kursi tamu", qty: "2", code: "01.05.12.2012", condition: "Baik" },
  { room: "Ruang WK I Bidang Akademik", name: "Meja kecil", qty: "1", code: "01.01.32.1990", condition: "Baik" },
  { room: "Ruang WK I Bidang Akademik", name: "Lemari dinding", qty: "1", code: "01.19.26.1996", condition: "Baik" },
  { room: "Ruang WK I Bidang Akademik", name: "Printer", qty: "1", code: "01.06.08.2013", condition: "Baik" },
  { room: "Ruang WK I Bidang Akademik", name: "Rak buku", qty: "1", code: "01.18.20.1990", condition: "Baik" },
  { room: "Ruang WK I Bidang Akademik", name: "CPU", qty: "1", code: "01.06.13.2013", condition: "Baik" },
  { room: "Ruang WK I Bidang Akademik", name: "Jam dinding", qty: "1", code: "01.11.04.2010", condition: "Baik" },
  { room: "Ruang WK I Bidang Akademik", name: "Keranjang sampah", qty: "1", code: "01.10.14.2019", condition: "Baik" },
  { room: "Ruang WK I Bidang Akademik", name: "AC", qty: "1", code: "", condition: "Baik" },

  { room: "Ruang Bendahara", name: "Meja kerja dosen", qty: "1", code: "01.01.27.1990", condition: "Baik" },
  { room: "Ruang Bendahara", name: "Kursi kerja dosen", qty: "1", code: "01.02.19.1990", condition: "Baik" },
  { room: "Ruang Bendahara", name: "Kursi tamu", qty: "2", code: "01.05.11.1996", condition: "Baik" },
  { room: "Ruang Bendahara", name: "Computer", qty: "1", code: "01.06.08.2013", condition: "Baik" },
  { room: "Ruang Bendahara", name: "CPU", qty: "1", code: "01.06.12.2013", condition: "Baik" },
  { room: "Ruang Bendahara", name: "Printer", qty: "1", code: "01.06.07.2013", condition: "Baik" },
  { room: "Ruang Bendahara", name: "Lemari arsip (file cabinet)", qty: "1", code: "01.19.24.1990", condition: "Baik" },
  { room: "Ruang Bendahara", name: "Rak buku", qty: "1", code: "01.18.19.2016", condition: "Baik" },
  { room: "Ruang Bendahara", name: "Kipas", qty: "1", code: "", condition: "Baik" },

  { room: "Ruang WK II Bidang Keuangan dan Kepegawaian", name: "Meja kerja dosen", qty: "1", code: "01.01.22.2019", condition: "Baik" },
  { room: "Ruang WK II Bidang Keuangan dan Kepegawaian", name: "Meja kecil", qty: "1", code: "01.01.23.2010", condition: "Baik" },
  { room: "Ruang WK II Bidang Keuangan dan Kepegawaian", name: "Kursi kerja dosen", qty: "2", code: "01.02.15.2012", condition: "Baik" },
  { room: "Ruang WK II Bidang Keuangan dan Kepegawaian", name: "Kursi tamu", qty: "2", code: "01.05.08.1990", condition: "1 kurang baik" },
  { room: "Ruang WK II Bidang Keuangan dan Kepegawaian", name: "Lemari dinding", qty: "1", code: "01.19.20.2000", condition: "Kurang baik" },
  { room: "Ruang WK II Bidang Keuangan dan Kepegawaian", name: "Keranjang sampah", qty: "1", code: "01.10.09.2021", condition: "Baik" },
  { room: "Ruang WK II Bidang Keuangan dan Kepegawaian", name: "Kipas angina", qty: "1", code: "01.07.13.2000", condition: "Baik" },
  { room: "Ruang WK II Bidang Keuangan dan Kepegawaian", name: "Colokan CCTV", qty: "1", code: "01.13.11.2021", condition: "Baik" },
  { room: "Ruang WK II Bidang Keuangan dan Kepegawaian", name: "Computer", qty: "1", code: "Pinjaman dari perpustakaan", condition: "Kurang baik" },

  { room: "Ruang ADAK", name: "Meja kerja dosen", qty: "2", code: "01.01.35.2013", condition: "Baik" },
  { room: "Ruang ADAK", name: "Kursi dosen", qty: "2", code: "01.02.24.1994", condition: "Baik" },
  { room: "Ruang ADAK", name: "Computer", qty: "1", code: "01.06.10.2013", condition: "Baik" },
  { room: "Ruang ADAK", name: "CPU", qty: "3", code: "01.06.14.2013", condition: "2 rusak" },
  { room: "Ruang ADAK", name: "Printer", qty: "1", code: "01.19.28.1996", condition: "Baik" },
  { room: "Ruang ADAK", name: "Cabinet file", qty: "1", code: "01.19.29.2010", condition: "Baik" },
  { room: "Ruang ADAK", name: "Kursi tamu", qty: "2", code: "01.05.13.2018", condition: "Baik" },
  { room: "Ruang ADAK", name: "Rak buku", qty: "1", code: "", condition: "Baik" },

  { room: "Ruang Kaprodi Teologi", name: "Meja kerja dosen", qty: "2", code: "01.01.26.2010", condition: "Baik" },
  { room: "Ruang Kaprodi Teologi", name: "Kursi kerja dosen", qty: "2", code: "01.02.18.1999", condition: "Baik" },
  { room: "Ruang Kaprodi Teologi", name: "Meja tempat arsip", qty: "1", code: "01.01.28.2000", condition: "Baik" },
  { room: "Ruang Kaprodi Teologi", name: "Lemari arsip (file cabinet)", qty: "1", code: "01.19.23.1990", condition: "Baik" },
  { room: "Ruang Kaprodi Teologi", name: "Rak buku", qty: "3", code: "01.18.18.2020", condition: "Baik" },
  { room: "Ruang Kaprodi Teologi", name: "AC", qty: "1", code: "01.07.06.2013", condition: "Baik" },
  { room: "Ruang Kaprodi Teologi", name: "CPU", qty: "1", code: "01.06.11.2001", condition: "Baik" },
  { room: "Ruang Kaprodi Teologi", name: "Printer", qty: "1", code: "01.06.06.2013", condition: "Baik" },
  { room: "Ruang Kaprodi Teologi", name: "Computer", qty: "1", code: "01.06.07.2001", condition: "Baik" },
  { room: "Ruang Kaprodi Teologi", name: "Madding", qty: "1", code: "01.32.09.2000", condition: "Baik" },
  { room: "Ruang Kaprodi Teologi", name: "Figura struktur prodi Teologi", qty: "1", code: "01.17.45.2000", condition: "Baik" },
  { room: "Ruang Kaprodi Teologi", name: "Figura visi misi teologi", qty: "1", code: "01.17.47.2021", condition: "Baik" },
  { room: "Ruang Kaprodi Teologi", name: "Figura foto wisuda", qty: "1", code: "01.17.49.2015", condition: "Baik" },
  { room: "Ruang Kaprodi Teologi", name: "Jam dinding", qty: "2", code: "01.11.03.2015", condition: "Rusak" },
  { room: "Ruang Kaprodi Teologi", name: "Box file beridiri", qty: "4", code: "01.20.35.2010", condition: "Baik" },
  { room: "Ruang Kaprodi Teologi", name: "Kursi tamu", qty: "2", code: "01.05.10.1999", condition: "Baik" },

  { room: "Ruang Sekretaris Prodi Teologi", name: "Meja kerja dosen", qty: "2", code: "01.01.33.2012", condition: "Baik" },
  { room: "Ruang Sekretaris Prodi Teologi", name: "Kursi kerja dosen", qty: "1", code: "01.02.23.2019", condition: "Baik" },
  { room: "Ruang Sekretaris Prodi Teologi", name: "Meja printer", qty: "1", code: "01.01.34.2012", condition: "Baik" },
  { room: "Ruang Sekretaris Prodi Teologi", name: "Computer", qty: "1", code: "01.06.09.2013", condition: "Baik" },
  { room: "Ruang Sekretaris Prodi Teologi", name: "CPU", qty: "1", code: "01.06.14.2013", condition: "Baik" },
  { room: "Ruang Sekretaris Prodi Teologi", name: "Printer", qty: "1", code: "01.06.09.2015", condition: "Baik" },
  { room: "Ruang Sekretaris Prodi Teologi", name: "Lemari kabinet", qty: "1", code: "01.19.27.2018", condition: "Baik" },
  { room: "Ruang Sekretaris Prodi Teologi", name: "Rak buku", qty: "3", code: "01.18.21.2015", condition: "Baik" },
  { room: "Ruang Sekretaris Prodi Teologi", name: "Madding", qty: "1", code: "01.32.11.2012", condition: "Baik" },
  { room: "Ruang Sekretaris Prodi Teologi", name: "OPS", qty: "1", code: "01.06.01.2020", condition: "Baik" },

  { room: "Ruang Kaprodi PAK", name: "Meja kerja dosen", qty: "4", code: "01.01.22.2010", condition: "Baik" },
  { room: "Ruang Kaprodi PAK", name: "Kursi kerja dosen", qty: "3", code: "01.02.15.2010", condition: "Baik" },
  { room: "Ruang Kaprodi PAK", name: "Kursi tamu", qty: "1", code: "01.05.01.2012", condition: "Baik" },
  { room: "Ruang Kaprodi PAK", name: "Computer", qty: "1", code: "01.06.06.2010", condition: "Rusak" },
  { room: "Ruang Kaprodi PAK", name: "CPU", qty: "1", code: "01.06.10.2010", condition: "Rusak" },
  { room: "Ruang Kaprodi PAK", name: "Rak buku", qty: "1", code: "01.18.15.2010", condition: "Baik" },
  { room: "Ruang Kaprodi PAK", name: "Lemari plastik", qty: "2", code: "01.19.19.2010", condition: "Baik" },
  { room: "Ruang Kaprodi PAK", name: "Loudspeaker", qty: "1", code: "01.06.05.2010", condition: "Rusak" },
  { room: "Ruang Kaprodi PAK", name: "AC", qty: "1", code: "01.07.05.2013", condition: "Baik" },
  { room: "Ruang Kaprodi PAK", name: "Madding", qty: "1", code: "01.32.05.2010", condition: "Baik" },
  { room: "Ruang Kaprodi PAK", name: "Struktur organisasi", qty: "1", code: "01.17.21.2010", condition: "Baik" },
  { room: "Ruang Kaprodi PAK", name: "Sertifikat akreditas", qty: "1", code: "01.17.22.2010", condition: "Baik" },
  { room: "Ruang Kaprodi PAK", name: "Visi misi PAK", qty: "1", code: "01.17.25.2018", condition: "Baik" },

  { room: "Ruang Sekretaris Prodi PAK", name: "Computer", qty: "1", code: "01.06.05.2016", condition: "Baik" },
  { room: "Ruang Sekretaris Prodi PAK", name: "Printer", qty: "1", code: "01.06.05.2018", condition: "Baik" },
  { room: "Ruang Sekretaris Prodi PAK", name: "CPU", qty: "1", code: "01.06.09.2016", condition: "Baik" },
  { room: "Ruang Sekretaris Prodi PAK", name: "Speaker", qty: "-", code: "01.06.04.2016", condition: "" },
  { room: "Ruang Sekretaris Prodi PAK", name: "Kipas angin", qty: "-", code: "01.07.12.2015", condition: "" },
  { room: "Ruang Sekretaris Prodi PAK", name: "Meja kerja", qty: "1", code: "01.01.20.2010", condition: "Baik" },
  { room: "Ruang Sekretaris Prodi PAK", name: "Kursi kerja", qty: "1", code: "01.02.12.2010", condition: "Baik" },
  { room: "Ruang Sekretaris Prodi PAK", name: "Rak buku", qty: "2", code: "01.18.14.2019", condition: "Baik" },
  { room: "Ruang Sekretaris Prodi PAK", name: "Skavolt", qty: "1", code: "01.06.01.2010", condition: "Rusak" },
  { room: "Ruang Sekretaris Prodi PAK", name: "Kursi kerja dosen", qty: "1", code: "01.02.13.2010", condition: "Baik" },

  { room: "Ruang Sekretaris Pasca Sarjana (Dan WK III)", name: "Lemari arsip", qty: "1", code: "01.19.17.1990", condition: "Baik" },
  { room: "Ruang Sekretaris Pasca Sarjana (Dan WK III)", name: "Meja kerja dosen", qty: "1", code: "01.01.11.1989", condition: "Baik" },
  { room: "Ruang Sekretaris Pasca Sarjana (Dan WK III)", name: "Kursi kerja dosen", qty: "2", code: "01.02.09.1996", condition: "Baik" },
  { room: "Ruang Sekretaris Pasca Sarjana (Dan WK III)", name: "Kursi tamu", qty: "2", code: "01.05.05.2012", condition: "Baik" },
  { room: "Ruang Sekretaris Pasca Sarjana (Dan WK III)", name: "Computer", qty: "1", code: "01.06.04.2010", condition: "Baik" },
  { room: "Ruang Sekretaris Pasca Sarjana (Dan WK III)", name: "Printer", qty: "2", code: "01.06.04.2011", condition: "Baik" },
  { room: "Ruang Sekretaris Pasca Sarjana (Dan WK III)", name: "CPU", qty: "1", code: "01.06.06.2007", condition: "Baik" },
  { room: "Ruang Sekretaris Pasca Sarjana (Dan WK III)", name: "Meja printer", qty: "1", code: "01.01.20.2007", condition: "Baik" },
  { room: "Ruang Sekretaris Pasca Sarjana (Dan WK III)", name: "Lemari dinding", qty: "1", code: "01.19.16.2000", condition: "Baik" },
  { room: "Ruang Sekretaris Pasca Sarjana (Dan WK III)", name: "White board", qty: "1", code: "01.17.01.2011", condition: "Baik" },
  { room: "Ruang Sekretaris Pasca Sarjana (Dan WK III)", name: "Keranjang sampah", qty: "1", code: "01.10.03.2015", condition: "Baik" },
  { room: "Ruang Sekretaris Pasca Sarjana (Dan WK III)", name: "Kipas", qty: "1", code: "01.07.06.2000", condition: "Baik" },
  { room: "Ruang Sekretaris Pasca Sarjana (Dan WK III)", name: "Figura logo sani", qty: "-", code: "01.17.15.1982", condition: "" },
  { room: "Ruang Sekretaris Pasca Sarjana (Dan WK III)", name: "Kontener plastic", qty: "-", code: "01.21.01.2021", condition: "" },
  { room: "Ruang Sekretaris Pasca Sarjana (Dan WK III)", name: "Box file folder berdiri", qty: "1", code: "01.20.09.2015", condition: "Baik" },
  { room: "Ruang Sekretaris Pasca Sarjana (Dan WK III)", name: "Meja dosen", qty: "1", code: "01.01.12.1990", condition: "Baik" },
  { room: "Ruang Sekretaris Pasca Sarjana (Dan WK III)", name: "Kursi dosen", qty: "1", code: "01.02.10.1990", condition: "Baik" },

  { room: "Ruang Sekretaris Umum", name: "Meja kerja dosen", qty: "3", code: "01.01.02.2000", condition: "Baik" },
  { room: "Ruang Sekretaris Umum", name: "Meja kecil", qty: "1", code: "01.01.06.2000", condition: "Baik" },
  { room: "Ruang Sekretaris Umum", name: "AC", qty: "1", code: "01.07.02.2010", condition: "Baik" },
  { room: "Ruang Sekretaris Umum", name: "Rak buku", qty: "3", code: "01.18.02.2015", condition: "Baik" },
  { room: "Ruang Sekretaris Umum", name: "Lemari arsip", qty: "4", code: "01.19.01.2020", condition: "Baik" },
  { room: "Ruang Sekretaris Umum", name: "Telepon", qty: "1", code: "01.15.01.1995", condition: "Rusak" },
  { room: "Ruang Sekretaris Umum", name: "Folder berdiri", qty: "-", code: "01.20.01.2017", condition: "" },
  { room: "Ruang Sekretaris Umum", name: "Wi-Fi", qty: "1", code: "01.15.01.2021", condition: "Baik" },
  { room: "Ruang Sekretaris Umum", name: "Computer", qty: "1", code: "01.06.01.2017", condition: "Baik" },
  { room: "Ruang Sekretaris Umum", name: "Printer", qty: "2", code: "01.06.02.2000", condition: "Baik" },
  { room: "Ruang Sekretaris Umum", name: "CPU", qty: "1", code: "01.06.01.2017", condition: "Baik" },
  { room: "Ruang Sekretaris Umum", name: "Loudspeaker", qty: "-", code: "01.06.01.2017", condition: "" },
  { room: "Ruang Sekretaris Umum", name: "Kursi dosen", qty: "1", code: "01.02.03.2000", condition: "Baik" },

  { room: "Ruang Tamu", name: "Mebel tamu (meja tamu)", qty: "1", code: "01.05.02.2014", condition: "Baik" },
  { room: "Ruang Tamu", name: "Kursi tamu", qty: "4", code: "01.05.06.2014", condition: "Baik" },
  { room: "Ruang Tamu", name: "Wi-Fi", qty: "1", code: "01.15.02.2017", condition: "Baik" },
  { room: "Ruang Tamu", name: "Kipas angin", qty: "1", code: "01.07.12.2000", condition: "Baik" },
  { room: "Ruang Tamu", name: "Figura sertifikan pendidikan", qty: "1", code: "01.17.20.2018", condition: "Baik" },
  { room: "Ruang Tamu", name: "Cermin", qty: "1", code: "01.10.04.2018", condition: "Baik" },
  { room: "Ruang Tamu", name: "Hand sanitizer", qty: "-", code: "01.10.05.2019", condition: "" },
  { room: "Ruang Tamu", name: "Meja alat rumah tangga", qty: "1", code: "01.09.20.2010", condition: "Baik" },
  { room: "Ruang Tamu", name: "Dispenser", qty: "1", code: "01.09.01.2010", condition: "Baik" },

  { room: "Gedung Perpustakaan", name: "Meja kerja dosen", qty: "1", code: "01.01.08.1990", condition: "Baik" },
  { room: "Gedung Perpustakaan", name: "Kursi kerja", qty: "2", code: "01.02.06.1990", condition: "Baik" },
  { room: "Gedung Perpustakaan", name: "Rak buku", qty: "6", code: "01.18.12.1990", condition: "Baik" },
  { room: "Gedung Perpustakaan", name: "Computer", qty: "4", code: "01.06.03.2013", condition: "Baik" },
  { room: "Gedung Perpustakaan", name: "Printer", qty: "1", code: "01.06.03.2013", condition: "Baik" },
  { room: "Gedung Perpustakaan", name: "CPU", qty: "1", code: "01.06.04.2013", condition: "Baik" },
  { room: "Gedung Perpustakaan", name: "CPU kecil", qty: "3", code: "01.06.06.2013", condition: "Baik" },
  { room: "Gedung Perpustakaan", name: "Kipas", qty: "3", code: "01.07.05.1990", condition: "Baik" },
  { room: "Gedung Perpustakaan", name: "Lemari buku", qty: "2", code: "01.19.09.2021", condition: "Baik" },
  { room: "Gedung Perpustakaan", name: "Meja belajar mahasiswa", qty: "11", code: "01.03.20.1990", condition: "Baik" },
  { room: "Gedung Perpustakaan", name: "Kursi belajar mahasiswa", qty: "31", code: "01.04.26.1990", condition: "Baik" },
  { room: "Gedung Perpustakaan", name: "Mesin photo copy", qty: "1", code: "01.12.01.2019", condition: "Pindah SekUm" },
  { room: "Gedung Perpustakaan", name: "AC", qty: "5", code: "01.07.04.2013", condition: "Baik" },
  { room: "Gedung Perpustakaan", name: "Tempat koran", qty: "1", code: "01.22.01.1990", condition: "Baik" },
  { room: "Gedung Perpustakaan", name: "Meja roda", qty: "2", code: "01.23.01.1990", condition: "Baik" },
  { room: "Gedung Perpustakaan", name: "Laci catalog manual", qty: "2", code: "01.24.02.1990", condition: "Baik" },
  { room: "Gedung Perpustakaan", name: "Lemari arsip", qty: "4", code: "01.19.07.1990", condition: "Baik" },
  { room: "Gedung Perpustakaan", name: "Lemari plastic", qty: "1", code: "01.19.09.2017", condition: "Baik" },
  { room: "Gedung Perpustakaan", name: "Lemari penitipan", qty: "1", code: "01.19.13.1990", condition: "Baik" },
  { room: "Gedung Perpustakaan", name: "Lemari petugas", qty: "1", code: "01.19.15.1990", condition: "Baik" },
  { room: "Gedung Perpustakaan", name: "Jam dinding", qty: "1", code: "01.11.02.2020", condition: "Baik" },
  { room: "Gedung Perpustakaan", name: "Masin ketik", qty: "1", code: "01.06.01.1990", condition: "Tdk dipakai" },
  { room: "Gedung Perpustakaan", name: "Keranjang buku besar", qty: "4", code: "01.26.04.2020", condition: "Baik" },
  { room: "Gedung Perpustakaan", name: "Kerajang buku kecil", qty: "2", code: "01.26.06.1990", condition: "Baik" },
  { room: "Gedung Perpustakaan", name: "Figura gambar Yerusalem", qty: "1", code: "01.17.05.1990", condition: "Baik" },
  { room: "Gedung Perpustakaan", name: "Figura gambar Peta", qty: "4", code: "01.17.09.1990", condition: "Baik" },
  { room: "Gedung Perpustakaan", name: "Figura visi misi PAK", qty: "1", code: "01.17.10.2018", condition: "Baik" },
  { room: "Gedung Perpustakaan", name: "Figura gambar Garuda Pancasila", qty: "1", code: "01.17.11.1990", condition: "Baik" },
  { room: "Gedung Perpustakaan", name: "Figura Sertifikat perpustakaan Forppti", qty: "1", code: "01.17.13.2021", condition: "Baik" },
  { room: "Gedung Perpustakaan", name: "Alat prakot", qty: "1", code: "01.27.01.2017", condition: "Baik" },
  { room: "Gedung Perpustakaan", name: "Londspeaker", qty: "1", code: "01.06.02.2017", condition: "Baik" },
  { room: "Gedung Perpustakaan", name: "Tempat kartu peminjaman buku (dosen)", qty: "1", code: "01.28.01.1990", condition: "Baik" },
  { room: "Gedung Perpustakaan", name: "Tempat kartu peminjaman buku (mahasiswa)", qty: "1", code: "01.28.02.1990", condition: "Baik" },
  { room: "Gedung Perpustakaan", name: "Telepon", qty: "1", code: "01.15.03.1990", condition: "Baik" },
  { room: "Gedung Perpustakaan", name: "Figura penghargaan GKN Jogja", qty: "-", code: "01.17.14.2008", condition: "Baik" },
  { room: "Gedung Perpustakaan", name: "Wi-Fi", qty: "1", code: "01.15.03.2017", condition: "Baik" },
  { room: "Gedung Perpustakaan", name: "Tempat sampah", qty: "1", code: "01.10.02.2020", condition: "Baik" },
  { room: "Gedung Perpustakaan", name: "Figura Brian Dugan", qty: "1", code: "02.17.30.1991", condition: "Baik" },
  { room: "Gedung Perpustakaan", name: "Figura Moore Halt", qty: "1", code: "02.17.31.1984", condition: "Baik" },
  { room: "Gedung Perpustakaan", name: "Hand sanitizer", qty: "-", code: "02.10.03.2019", condition: "-" },
  { room: "Gedung Perpustakaan", name: "Ember suci tangan", qty: "-", code: "02.10.03.2019", condition: "Baik" },
  { room: "Gedung Perpustakaan", name: "Keranjang sampah", qty: "1", code: "02.10.02.2019", condition: "Baik" },

  { room: "Laboratorium Komputer", name: "Laptop", qty: "14", code: "01.06.14.2014", condition: "Baik" },
  { room: "Laboratorium Komputer", name: "PC", qty: "1", code: "", condition: "Baik" },
  { room: "Laboratorium Komputer", name: "Kursi", qty: "15", code: "01.04.16.2014", condition: "Baik" },
  { room: "Laboratorium Komputer", name: "Meja", qty: "12", code: "01.03.14.2014", condition: "Baik" },
  { room: "Laboratorium Komputer", name: "AC", qty: "2", code: "01.07.02.2014", condition: "Baik" },
  { room: "Laboratorium Komputer", name: "Kipas", qty: "1", code: "01.07.01.2014", condition: "Baik" },
  { room: "Laboratorium Komputer", name: "White board", qty: "1", code: "01.32.01.2014", condition: "Baik" },
  { room: "Laboratorium Komputer", name: "LCD", qty: "1", code: "01.06.01.2014", condition: "Baik" },
  { room: "Laboratorium Komputer", name: "Server / WiFi", qty: "1", code: "01.15.01.2014", condition: "Baik" },
  { room: "Laboratorium Komputer", name: "Komputer", qty: "1", code: "01.06.01.2014", condition: "Baik" },
  { room: "Laboratorium Komputer", name: "Printer", qty: "1", code: "01.06.01.2014", condition: "Baik" },
  { room: "Laboratorium Komputer", name: "CPU", qty: "1", code: "01.06.01.2014", condition: "Baik" },
  { room: "Laboratorium Komputer", name: "Lemari", qty: "1", code: "01.19.01.2014", condition: "Baik" },
  { room: "Laboratorium Komputer", name: "Ember", qty: "1", code: "01.10.02.2020", condition: "Baik" },
  { room: "Laboratorium Komputer", name: "Tempat sampah", qty: "2", code: "01.10.02.2020", condition: "Baik" },
  { room: "Laboratorium Komputer", name: "Wi-Fi", qty: "1", code: "02.15.05.2017", condition: "Baik" },

  { room: "Gedung Kapel", name: "Kursi kapel warna cokelat", qty: "21", code: "01.34.23.1992", condition: "1 Kurang Baik" },
  { room: "Gedung Kapel", name: "Kursi kapel warna merah maroon", qty: "14", code: "01.34.12.2019", condition: "Baik" },
  { room: "Gedung Kapel", name: "Kursi kapel warna biru", qty: "1", code: "01.34.04.2012", condition: "Baik" },
  { room: "Gedung Kapel", name: "Mimbar kapel", qty: "1", code: "01.33.01.1992", condition: "Baik" },
  { room: "Gedung Kapel", name: "Lemari", qty: "1", code: "01.19.01.1992", condition: "Baik" },
  { room: "Gedung Kapel", name: "Figura gambar garuda", qty: "1", code: "01.17.01.1992", condition: "Baik" },
  { room: "Gedung Kapel", name: "Meja", qty: "2", code: "01.03.03.1992", condition: "Baik" },
  { room: "Gedung Kapel", name: "LCD", qty: "1", code: "01.34.01.2019", condition: "Baik" },
  { room: "Gedung Kapel", name: "Jam dinding", qty: "1", code: "01.34.02.2018", condition: "Baik" },
  { room: "Gedung Kapel", name: "Kursi kapel monitor", qty: "1", code: "01.34.01.1996", condition: "Baik" },
  { room: "Gedung Kapel", name: "Sound", qty: "1", code: "01.06.01.1995", condition: "Baik" },
  { room: "Gedung Kapel", name: "Figura", qty: "1", code: "01.17.04.2000", condition: "Baik" },
  { room: "Gedung Kapel", name: "Keranjang sampah", qty: "1", code: "02.10.03.2019", condition: "Baik" },
  { room: "Gedung Kapel", name: "Kajon", qty: "1", code: "01.36.01.2015", condition: "Kurang Baik" },
  { room: "Gedung Kapel", name: "Drum", qty: "1", code: "01.36.01.2005", condition: "Kurang Baik" },
  { room: "Gedung Kapel", name: "Gitar bass listrik", qty: "1", code: "01.36.01.2005", condition: "Baik" },
  { room: "Gedung Kapel", name: "Gitar listrik", qty: "1", code: "01.36.02.2005", condition: "Rusak" },
  { room: "Gedung Kapel", name: "Londspeaker besar", qty: "2", code: "01.36.01.2005", condition: "Baik" },
  { room: "Gedung Kapel", name: "Londspeaker kecil", qty: "2", code: "01.36.07.2005", condition: "Baik" },
  { room: "Gedung Kapel", name: "Tempat kertas lirik lagu", qty: "2", code: "01.36.01.2005", condition: "Kurang Baik" },

  { room: "Gedung Asrama Putra", name: "Kamar atas", qty: "8", code: "", condition: "Baik" },
  { room: "Gedung Asrama Putra", name: "Kamar bawah", qty: "5", code: "", condition: "Pengecatan" },
  { room: "Gedung Asrama Putra", name: "Ruang doa", qty: "", code: "", condition: "Baik" },
  { room: "Gedung Asrama Putra", name: "Ruang bapak asrama", qty: "1", code: "", condition: "Kurang Baik" },
  { room: "Gedung Asrama Putra", name: "Kamar mandi", qty: "12", code: "", condition: "Baik" },
  { room: "Gedung Asrama Putra", name: "Tempat tidur", qty: "26", code: "01.35.24.1987", condition: "14 kurang Baik" },
  { room: "Gedung Asrama Putra", name: "Meja", qty: "14", code: "01.30.01.1987", condition: "1 rusak" },
  { room: "Gedung Asrama Putra", name: "Kursi kamar", qty: "13", code: "01.04.25.1987", condition: "Baik" },
  { room: "Gedung Asrama Putra", name: "Lemari", qty: "", code: "", condition: "Baik" },
  { room: "Gedung Asrama Putra", name: "Kursi ruang tamu", qty: "6", code: "01.05.01.1987", condition: "Baik" },
  { room: "Gedung Asrama Putra", name: "Meja ruang tamu", qty: "2", code: "01.05.01.1987", condition: "1 rusak" },
  { room: "Gedung Asrama Putra", name: "Dispenser", qty: "1", code: "01.09.01.2015", condition: "Rusak" },
  { room: "Gedung Asrama Putra", name: "Lemari lama", qty: "21", code: "01.19.20.1987", condition: "2 rusak" },
  { room: "Gedung Asrama Putra", name: "Lemari plastic", qty: "4", code: "01.19.26.2019", condition: "Baik" },
  { room: "Gedung Asrama Putra", name: "Lemari baru", qty: "1", code: "01.19.01.2020", condition: "Baik" },

  { room: "Gedung Asrama Putri", name: "Kamar tidur (atas & bawah)", qty: "12", code: "", condition: "Baik" },
  { room: "Gedung Asrama Putri", name: "Kamar mandi", qty: "12", code: "", condition: "9 kurang baik/rusak" },
  { room: "Gedung Asrama Putri", name: "Gudang", qty: "3", code: "", condition: "Baik" },
  { room: "Gedung Asrama Putri", name: "Tempat tidur", qty: "48", code: "01.35.26.2017", condition: "3 rusak" },
  { room: "Gedung Asrama Putri", name: "Meja", qty: "48", code: "01.03.26.2004", condition: "10 rusak" },
  { room: "Gedung Asrama Putri", name: "Kursi kamar", qty: "32", code: "01.04.35.2018", condition: "4 rusak" },
  { room: "Gedung Asrama Putri", name: "Lemari", qty: "24", code: "01.19.28.2019", condition: "4 rusak" },
  { room: "Gedung Asrama Putri", name: "Kursi ruang tamu", qty: "4", code: "01.05.01.2004", condition: "1 rusak" },
  { room: "Gedung Asrama Putri", name: "Meja ruang tamu", qty: "2", code: "01.05.01.2004", condition: "Baik" },
  { room: "Gedung Asrama Putri", name: "Cermin", qty: "12", code: "01.10.01.2004", condition: "Baik" },
  { room: "Gedung Asrama Putri", name: "Mading", qty: "1", code: "01.32.01.2004", condition: "Baik" },
  { room: "Gedung Asrama Putri", name: "Tikar besar", qty: "2", code: "01.35.01.2004", condition: "Baik" },
  { room: "Gedung Asrama Putri", name: "Wi-Fi", qty: "2", code: "01.15.01.2004", condition: "Baik" },
  { room: "Gedung Asrama Putri", name: "Wastafel", qty: "3", code: "01.10.01.2004", condition: "1 rusak" },
  { room: "Gedung Asrama Putri", name: "Jam", qty: "12", code: "01.11.02.2015", condition: "1 rusak" },
  { room: "Gedung Asrama Putri", name: "Kursi gudang", qty: "", code: "01.04.38.2018", condition: "" },
  { room: "Gedung Asrama Putri", name: "Ember cuci tangan", qty: "", code: "02.10.01.2019", condition: "" },

  { room: "Lobby Utama", name: "Madding", qty: "1", code: "01.32.08.1984", condition: "Baik" },
  { room: "Lobby Utama", name: "Figura doa", qty: "1", code: "01.17.32.2011", condition: "Baik" },
  { room: "Lobby Utama", name: "Figura Alkitab Nazarene Indonesia", qty: "1", code: "01.17.33.1984", condition: "Baik" },
  { room: "Lobby Utama", name: "CCTV", qty: "1", code: "01.13.02.2021", condition: "Baik" },
  { room: "Lobby Utama", name: "Figura foto presiden dan wakil presiden RI", qty: "1", code: "01.17.34.2019", condition: "Baik" },
  { room: "Lobby Utama", name: "Figura gambar Garuda Pancasila", qty: "1", code: "01.17.36.1984", condition: "Baik" },
  { room: "Lobby Utama", name: "Wi-Fi", qty: "1", code: "01.15.04.2017", condition: "Baik" },
  { room: "Lobby Utama", name: "Figura gambar alam", qty: "1", code: "01.17.36.2000", condition: "Baik" },
  { room: "Lobby Utama", name: "Figura foto (Rev. Robert D. Mccrosky, Rev. Mchael P. Mccary, Pdt. Stephanus Hartoyo, Pdt. Kuncara Candra, Pdt. Yanpeth Wambrauw)", qty: "1", code: "01.17.37.1985 / 01.17.38.1988 / 01.17.39.1989 / 01.17.40.1994 / 01.17.55.2000", condition: "Baik" },
  { room: "Lobby Utama", name: "Figura gambar Yesus", qty: "1", code: "01.17.41.2001", condition: "Baik" },

  { room: "Pos Keamanan", name: "Meja kerja", qty: "1", code: "01.01.29.2000", condition: "Baik" },
  { room: "Pos Keamanan", name: "Kursi kerja", qty: "1", code: "01.02.19.1999", condition: "Baik" },
  { room: "Pos Keamanan", name: "Lemari dinding", qty: "1 (3 kotak)", code: "01.19.24.1999", condition: "1 kotak rusak" },
  { room: "Pos Keamanan", name: "Kursi tamu", qty: "1", code: "01.05.14.2015", condition: "Baik" },
  { room: "Pos Keamanan", name: "Hand sanitizer", qty: "-", code: "01.01.06.2019", condition: "-" },
  { room: "Pos Keamanan", name: "Pengecek suhu", qty: "-", code: "01.10.01.2019", condition: "-" },
  { room: "Pos Keamanan", name: "Sprot covid (besar)", qty: "-", code: "01.10.07.2021", condition: "-" },

  { room: "Gudang", name: "Mesin potong rumput", qty: "3", code: "01.10.03.2010", condition: "2 rusak" },
  { room: "Gudang", name: "Ember", qty: "4", code: "01.10.06.2010", condition: "2 rusak" },
  { room: "Gudang", name: "Baskom", qty: "-", code: "01.10.07.2010", condition: "" },

  { room: "Wisma Tamu", name: "Meja tamu", qty: "1", code: "01.05.02.2010", condition: "Baik" },
  { room: "Wisma Tamu", name: "Kursi tamu", qty: "3", code: "01.05.04.2010", condition: "Baik" },
  { room: "Wisma Tamu", name: "Lemari kayu", qty: "1", code: "01.19.01.2005", condition: "Baik" },
  { room: "Wisma Tamu", name: "Lemari plastic", qty: "1", code: "01.19.02.2015", condition: "Baik" },
  { room: "Wisma Tamu", name: "Kipas", qty: "1", code: "01.07.01.2000", condition: "Rusak" },
  { room: "Wisma Tamu", name: "Wastafel", qty: "1", code: "01.10.01.1989", condition: "Kuran baik" },
  { room: "Wisma Tamu", name: "Kamar tidur", qty: "3", code: "01.30.04.1991", condition: "Baik" },
  { room: "Wisma Tamu", name: "Kamar mandi", qty: "1", code: "01.10.01.1991", condition: "Baik" },

  { room: "Lapangan Olah Raga", name: "Lapangan basket", qty: "1", code: "7m x 10m", condition: "Baik" },
  { room: "Lapangan Olah Raga", name: "Ring basket", qty: "1", code: "", condition: "Rusak" },
  { room: "Lapangan Olah Raga", name: "Tenis meja", qty: "1", code: "2m x 1,75m", condition: "Baik" },

  { room: "Kebun Buah", name: "Lampu", qty: "3", code: "02.06.03.2019", condition: "Kurang baik" },
  { room: "Kebun Buah", name: "Keran air", qty: "14", code: "02.10.14.2021", condition: "Baik" },
  { room: "Kebun Buah", name: "Selang air besar", qty: "30m", code: "", condition: "Kurang baik" },
  { room: "Kebun Buah", name: "Selang air kecil", qty: "17m", code: "", condition: "Baik" },
  { room: "Kebun Buah", name: "Alat penyiram tanaman", qty: "1", code: "", condition: "Baik" },
  { room: "Kebun Buah", name: "Gerobak sorong", qty: "1", code: "", condition: "Baik" },

  { room: "Kolam Ikan Buatan", name: "Kolam besar", qty: "", code: "12m x 7m", condition: "Baik" },
  { room: "Kolam Ikan Buatan", name: "Kolam kecil", qty: "", code: "5,75m x 2,75m", condition: "Baik" },
  { room: "Kolam Ikan Buatan", name: "Kolam sedang", qty: "", code: "4m x 3m", condition: "Baik" },
  { room: "Kolam Ikan Buatan", name: "Penampung air", qty: "", code: "", condition: "Baik" },

  { room: "Kolam Ikan Alami", name: "Kolam besar", qty: "", code: "15m x 6m", condition: "Kurang baik" },
  { room: "Kolam Ikan Alami", name: "Kolam sedang", qty: "", code: "12m x 4m", condition: "Kurang baik" },
  { room: "Kolam Ikan Alami", name: "Kolam kecil", qty: "", code: "14m x 5m", condition: "Kurang baik" },

  { room: "Ruangan Promosi (Ruang BEM / Ruang pak Hadi)", name: "Meja kerja dosen", qty: "2", code: "01.01.24.2015", condition: "Baik" },
  { room: "Ruangan Promosi (Ruang BEM / Ruang pak Hadi)", name: "Kursi kerja dosen", qty: "2", code: "01.02.17.1996", condition: "Baik" },
  { room: "Ruangan Promosi (Ruang BEM / Ruang pak Hadi)", name: "Kursi tamu", qty: "2", code: "01.05.09.2012", condition: "1 rusak" },
  { room: "Ruangan Promosi (Ruang BEM / Ruang pak Hadi)", name: "Kipas", qty: "1", code: "01.07.14.2000", condition: "Baik" },
  { room: "Ruangan Promosi (Ruang BEM / Ruang pak Hadi)", name: "Figura visi misi prodi S2", qty: "1", code: "01.17.43.1990", condition: "Baik" },
  { room: "Ruangan Promosi (Ruang BEM / Ruang pak Hadi)", name: "Figura sertifikat akreditasi", qty: "1", code: "01.17.44.2014", condition: "Baik" },
  { room: "Ruangan Promosi (Ruang BEM / Ruang pak Hadi)", name: "Lemari buku", qty: "1", code: "01.19.21.2000", condition: "Baik" },
  { room: "Ruangan Promosi (Ruang BEM / Ruang pak Hadi)", name: "Rak buku", qty: "1", code: "01.18.15.2000", condition: "Baik" },
  { room: "Ruangan Promosi (Ruang BEM / Ruang pak Hadi)", name: "Lemari arsip", qty: "1", code: "01.19.22.1990", condition: "Baik" },
  { room: "Ruangan Promosi (Ruang BEM / Ruang pak Hadi)", name: "Box file berdiri", qty: "1", code: "01.20.19.2010", condition: "Baik" },
  { room: "Ruangan Promosi (Ruang BEM / Ruang pak Hadi)", name: "Telepon", qty: "1", code: "01.15.04.1990", condition: "Baik" },
  { room: "Ruangan Promosi (Ruang BEM / Ruang pak Hadi)", name: "AC", qty: "1", code: "", condition: "Baik" },

  { room: "Luar Ruangan", name: "Wastafel", qty: "1", code: "02.10.01.1990", condition: "Kuran baik" },
  { room: "Luar Ruangan", name: "Bendera logo STTNI", qty: "1", code: "02.25.01.2000", condition: "Baik" },
  { room: "Luar Ruangan", name: "Wastafel cuci tangan", qty: "2", code: "02.10.07.2021", condition: "Kurang baik" },
  { room: "Luar Ruangan", name: "CCTV", qty: "8", code: "02.13.03.2021", condition: "Baik" },
  { room: "Luar Ruangan", name: "Figura MccRoskey Hall", qty: "1", code: "01.17.42.1984", condition: "Baik" },
  { room: "Luar Ruangan", name: "Mobil kampus", qty: "1", code: "02.16.01.2006", condition: "Kurang baik" },
  { room: "Luar Ruangan", name: "Sabun untuk bakteri", qty: "-", code: "01.10.10.2021", condition: "-" },
  { room: "Luar Ruangan", name: "Hand sanitizer", qty: "-", code: "02.10.02.2019", condition: "-" },
  { room: "Luar Ruangan", name: "Torn (penampung air)", qty: "1", code: "02.10.10.2000", condition: "Baik" },
  { room: "Luar Ruangan", name: "Ember cuci tangan", qty: "-", code: "02.10.01.2019", condition: "-" },
  { room: "Luar Ruangan", name: "Figura visi misi Teologi", qty: "", code: "02.17.28.2021", condition: "Baik" },
  { room: "Luar Ruangan", name: "Kursi", qty: "", code: "02.04.131.1990", condition: "" },
  { room: "Luar Ruangan", name: "Cermin", qty: "", code: "02.10.02.1990", condition: "-" },
  { room: "Luar Ruangan", name: "Meja", qty: "", code: "02.02.20.2018", condition: "" },
  { room: "Luar Ruangan", name: "Keranjang sampah", qty: "8", code: "02.10.12.2019", condition: "Baik" },
  { room: "Luar Ruangan", name: "Hand sanitizer", qty: "-", code: "02.10.12.2019", condition: "-" },

  { room: "Dapur", name: "Figura Frank Bye", qty: "", code: "01.29.01.1991", condition: "Baik" },
  { room: "Dapur", name: "Kursi kerja", qty: "1", code: "01.29.25.1990", condition: "Baik" },
  { room: "Dapur", name: "Meja kerja", qty: "1", code: "01.29.14.1990", condition: "Baik" },
  { room: "Dapur", name: "Kulkas", qty: "2", code: "01.29.02.1990", condition: "Baik" },
  { room: "Dapur", name: "Lemari", qty: "2", code: "01.29.01.1998", condition: "Baik" },
  { room: "Dapur", name: "Kursi plastic", qty: "2", code: "01.29.26.1990", condition: "Baik" },
  { room: "Dapur", name: "Meja kecil", qty: "1", code: "01.29.15.1990", condition: "Baik" },
  { room: "Dapur", name: "Motor", qty: "1", code: "01.29.01.2020", condition: "Baik" },
  { room: "Dapur", name: "Keranjang sampah", qty: "1", code: "02.29.01.2019", condition: "Baik" },
  { room: "Dapur", name: "Torn", qty: "2", code: "01.29.02.1988", condition: "1 rusak" },
  { room: "Dapur", name: "Jam", qty: "-", code: "01.11.01.2015", condition: "" },
  { room: "Dapur", name: "Kompor gas besar", qty: "1", code: "01.08.04.2020", condition: "Baik" },
  { room: "Dapur", name: "Tabung gas besar", qty: "4", code: "01.08.08.1991", condition: "Baik" },
  { room: "Dapur", name: "Tabung gas kecil", qty: "3", code: "01.08.11.2015", condition: "Baik" },
  { room: "Dapur", name: "Meja makan", qty: "11", code: "01.29.12.2019", condition: "1 kurang baik" },
  { room: "Dapur", name: "Kursi makan", qty: "23", code: "01.29.25.2019", condition: "Baik" },
  { room: "Dapur", name: "Kipas", qty: "2", code: "01.29.02.2000", condition: "1 rusak" },
  { room: "Dapur", name: "Wastafel", qty: "2", code: "01.29.02.2000", condition: "Baik" }
];
